/*
 * Stoatworks Labs - About window data for Ferric.
 *
 * ⚠️ HAND-WRITTEN, and the only file in the fleet's About block that ever is.
 * Every other repo's copy is GENERATED by stoatworks-backend/scripts/sync-about.py
 * from the website's projects.json, which is the one place these facts are
 * written down.
 *
 * This one is hand-written because Ferric has no projects.json entry yet --
 * adding one publishes a page, which is not something to do as a side effect of
 * scaffolding a repo. The values below are what that entry should say. Add the
 * entry, run the sync, and this file goes back to being generated like the
 * others; until then a sync would DELETE these rather than fill them in.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Ferric";
    inline constexpr auto slug = "ferric";
    inline constexpr auto hook = "Wow, flutter and tape noise reduction for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "https://stoatworks-labs.com/software/ferric/guide/";
    inline constexpr auto page = "https://stoatworks-labs.com/software/ferric/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/ferric";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
